spring:
  application:
    name: Unicode
  datasource:
    url: jdbc:mysql://localhost:3306/unicode
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true